"""
Core pack: world knowledge useful for any corpus — countries, regions and major cities,
international organizations, heads of state and government, militant groups, foreign
intelligence services, major companies and news organizations, and broad cross-cutting themes.

Entries: (canonical name, [aliases], description). Single-word aliases match case-sensitively,
multi-word aliases case-insensitively. Canonical names shared with other packs (e.g. sigint) are
merged. Descriptions are deliberately neutral; topic packs may override them.
Where a role is ongoing the description says "from YEAR".
"""

DESCRIPTION = "World knowledge: countries, cities, international bodies, leaders, groups, major companies, media"

_countries = [
    # name, aliases
    ("United States", ["United States", "U.S.", "USA", "America", "United States of America"]),
    ("United Kingdom", ["United Kingdom", "U.K.", "UK", "Britain", "Great Britain", "England", "Scotland", "Wales", "Northern Ireland"]),
    ("Canada", []), ("Australia", []), ("New Zealand", []),
    ("Germany", ["Federal Republic of Germany", "West Germany", "East Germany", "GDR", "FRG"]),
    ("France", []), ("Italy", []), ("Spain", []), ("Portugal", []), ("Ireland", []), ("Iceland", []),
    ("Netherlands", ["Holland", "The Netherlands"]), ("Belgium", []), ("Luxembourg", []), ("Switzerland", []),
    ("Austria", []), ("Liechtenstein", []), ("Monaco", []), ("Andorra", []), ("Malta", []), ("San Marino", []),
    ("Sweden", []), ("Norway", []), ("Denmark", []), ("Finland", []),
    ("Poland", []), ("Czech Republic", ["Czechia"]), ("Czechoslovakia", []), ("Slovakia", []), ("Hungary", []),
    ("Romania", []), ("Bulgaria", []), ("Greece", []), ("Cyprus", []), ("Turkey", ["Türkiye"]),
    ("Slovenia", []), ("Croatia", []), ("Serbia", []), ("Montenegro", []), ("Bosnia", ["Bosnia and Herzegovina", "Bosnia-Herzegovina"]),
    ("Kosovo", []), ("Albania", []), ("North Macedonia", ["Macedonia"]), ("Yugoslavia", []),
    ("Ukraine", []), ("Belarus", []), ("Moldova", []), ("Estonia", []), ("Latvia", []), ("Lithuania", []),
    ("Russia", ["Russian Federation", "USSR", "Soviet Union", "U.S.S.R."]),
    ("Georgia (country)", ["Republic of Georgia", "Tbilisi"]), ("Armenia", []), ("Azerbaijan", []),
    ("Kazakhstan", []), ("Uzbekistan", []), ("Turkmenistan", []), ("Kyrgyzstan", []), ("Tajikistan", []),
    ("China", ["PRC", "People's Republic of China", "Mainland China"]), ("Taiwan", ["Republic of China"]),
    ("Hong Kong", []), ("Macau", ["Macao"]), ("Mongolia", []), ("Japan", []),
    ("South Korea", ["ROK", "Republic of Korea"]), ("North Korea", ["DPRK", "Democratic People's Republic of Korea"]),
    ("India", []), ("Pakistan", []), ("Afghanistan", []), ("Bangladesh", []), ("Sri Lanka", []), ("Nepal", []),
    ("Bhutan", []), ("Maldives", []),
    ("Iran", ["Islamic Republic of Iran"]), ("Iraq", []), ("Syria", []), ("Lebanon", []), ("Israel", []),
    ("Palestinian territories", ["Gaza", "Gaza Strip", "West Bank", "Palestinian Authority", "Palestine"]),
    ("Jordan", []), ("Saudi Arabia", ["KSA", "Kingdom of Saudi Arabia"]), ("Yemen", []), ("Oman", []),
    ("United Arab Emirates", ["UAE", "Dubai", "Abu Dhabi"]), ("Qatar", []), ("Kuwait", []), ("Bahrain", []),
    ("Egypt", []), ("Libya", []), ("Tunisia", []), ("Algeria", []), ("Morocco", []), ("Western Sahara", []),
    ("Sudan", []), ("South Sudan", []), ("Ethiopia", []), ("Eritrea", []), ("Somalia", ["Somaliland"]), ("Djibouti", []),
    ("Kenya", []), ("Uganda", []), ("Tanzania", []), ("Rwanda", []), ("Burundi", []),
    ("Democratic Republic of the Congo", ["DRC", "DR Congo", "Zaire", "Congo-Kinshasa"]),
    ("Republic of the Congo", ["Congo-Brazzaville"]),
    ("Nigeria", []), ("Ghana", []), ("Ivory Coast", ["Côte d'Ivoire", "Cote d'Ivoire"]), ("Senegal", []), ("Mali", []),
    ("Niger", []), ("Chad", []), ("Burkina Faso", []), ("Mauritania", []), ("Guinea", []), ("Guinea-Bissau", []),
    ("Sierra Leone", []), ("Liberia", []), ("Togo", []), ("Benin", []), ("Cameroon", []), ("Gabon", []),
    ("Equatorial Guinea", []), ("Central African Republic", []), ("Gambia", ["The Gambia"]), ("Cape Verde", ["Cabo Verde"]),
    ("Angola", []), ("Zambia", []), ("Zimbabwe", []), ("Mozambique", []), ("Malawi", []), ("Namibia", []),
    ("Botswana", []), ("South Africa", []), ("Lesotho", []), ("Eswatini", ["Swaziland"]), ("Madagascar", []),
    ("Mauritius", []), ("Seychelles", []), ("Comoros", []),
    ("Indonesia", []), ("Malaysia", []), ("Singapore", []), ("Thailand", []), ("Philippines", []), ("Vietnam", ["Viet Nam"]),
    ("Burma", ["Myanmar"]), ("Cambodia", []), ("Laos", []), ("Brunei", []), ("Timor-Leste", ["East Timor"]),
    ("Papua New Guinea", []), ("Fiji", []), ("Samoa", []), ("Tonga", []), ("Vanuatu", []), ("Solomon Islands", []),
    ("Nauru", []), ("Tuvalu", []), ("Kiribati", []), ("Marshall Islands", []), ("Palau", []), ("Micronesia", []),
    ("Mexico", []), ("Guatemala", []), ("Belize", []), ("Honduras", []), ("El Salvador", []), ("Nicaragua", []),
    ("Costa Rica", []), ("Panama", []), ("Cuba", []), ("Haiti", []), ("Dominican Republic", []), ("Jamaica", []),
    ("Bahamas", ["The Bahamas"]), ("Trinidad and Tobago", []), ("Barbados", []),
    ("Colombia", []), ("Venezuela", []), ("Ecuador", []), ("Peru", []), ("Bolivia", []), ("Brazil", ["Brasil"]),
    ("Paraguay", []), ("Uruguay", []), ("Argentina", []), ("Chile", []), ("Guyana", []), ("Suriname", []),
]

_places = [
    ("Washington, D.C.", ["Washington, D.C.", "Washington DC", "Washington, DC", "Washington D.C."], "Capital of the United States."),
    ("New York", ["New York", "NYC", "New York City", "Manhattan"], ""),
    ("Langley", ["Langley, Virginia"], "Langley, Virginia: CIA headquarters."),
    ("Pentagon (building)", ["the Pentagon building"], "U.S. Department of Defense headquarters in Arlington, Virginia."),
    ("Guantanamo", ["Guantanamo", "Guantánamo", "GTMO", "Guantanamo Bay"], "U.S. naval base and detention facility in Cuba."),
    ("Abu Ghraib", ["Abu Ghraib", "Abu Ghuraib"], "Prison near Baghdad; site of detainee abuse by U.S. personnel exposed in 2004."),
    ("Bagram", ["Bagram", "Bagram Airfield", "Bagram Air Base"], "U.S. air base and detention facility in Afghanistan."),
    ("London", [], ""), ("Paris", [], ""), ("Berlin", [], ""), ("Bonn", [], ""), ("Frankfurt", [], ""), ("Munich", ["München"], ""),
    ("Hamburg", [], ""), ("Brussels", [], ""), ("The Hague", ["Den Haag"], ""), ("Amsterdam", [], ""), ("Geneva", [], ""),
    ("Zurich", ["Zürich"], ""), ("Vienna", [], ""), ("Rome", [], ""), ("Madrid", [], ""), ("Lisbon", [], ""), ("Dublin", [], ""),
    ("Copenhagen", [], ""), ("Stockholm", [], ""), ("Oslo", [], ""), ("Helsinki", [], ""), ("Reykjavik", ["Reykjavík"], ""),
    ("Warsaw", [], ""), ("Prague", [], ""), ("Budapest", [], ""), ("Bucharest", [], ""), ("Athens", [], ""),
    ("Belgrade", [], ""), ("Sarajevo", [], ""), ("Kyiv", ["Kiev"], ""), ("Minsk", [], ""), ("Moscow", [], ""),
    ("St. Petersburg", ["St. Petersburg", "Saint Petersburg", "Leningrad"], ""), ("Ankara", [], ""), ("Istanbul", [], ""),
    ("Beijing", ["Peking"], ""), ("Shanghai", [], ""), ("Tokyo", [], ""), ("Seoul", [], ""), ("Pyongyang", [], ""),
    ("Taipei", [], ""), ("New Delhi", ["Delhi"], ""), ("Mumbai", ["Bombay"], ""), ("Islamabad", [], ""), ("Karachi", [], ""),
    ("Lahore", [], ""), ("Abbottabad", [], ""), ("Kabul", [], ""), ("Kandahar", [], ""), ("Helmand", [], ""),
    ("Tehran", [], ""), ("Baghdad", [], ""), ("Basra", ["Basrah"], ""), ("Mosul", [], ""), ("Fallujah", ["Falluja"], ""),
    ("Damascus", [], ""), ("Aleppo", [], ""), ("Beirut", [], ""), ("Jerusalem", [], ""), ("Tel Aviv", [], ""),
    ("Amman", [], ""), ("Riyadh", [], ""), ("Jeddah", ["Jiddah"], ""), ("Doha", [], ""), ("Sanaa", ["Sana'a"], ""),
    ("Cairo", [], ""), ("Tripoli", [], ""), ("Benghazi", [], ""), ("Tunis", [], ""), ("Algiers", [], ""), ("Rabat", [], ""),
    ("Khartoum", [], ""), ("Addis Ababa", [], ""), ("Mogadishu", [], ""), ("Nairobi", [], ""), ("Lagos", [], ""),
    ("Abuja", [], ""), ("Kinshasa", [], ""), ("Johannesburg", [], ""), ("Pretoria", [], ""), ("Cape Town", [], ""),
    ("Jakarta", [], ""), ("Kuala Lumpur", [], ""), ("Bangkok", [], ""), ("Manila", [], ""), ("Hanoi", [], ""),
    ("Saigon", ["Ho Chi Minh City"], ""), ("Rangoon", ["Yangon"], ""), ("Canberra", [], ""), ("Sydney", [], ""),
    ("Wellington", [], ""), ("Ottawa", [], ""), ("Toronto", [], ""), ("Mexico City", [], ""), ("Havana", [], ""),
    ("Caracas", [], ""), ("Bogota", ["Bogotá"], ""), ("Lima", [], ""), ("Quito", [], ""), ("La Paz", [], ""),
    ("Santiago", [], ""), ("Buenos Aires", [], ""), ("Brasilia", ["Brasília"], ""), ("Rio de Janeiro", [], ""),
    ("Sao Paulo", ["São Paulo"], ""), ("Montevideo", [], ""), ("Panama City", [], ""), ("Miami", [], ""),
    ("Los Angeles", [], ""), ("San Francisco", [], ""), ("Chicago", [], ""), ("Houston", [], ""), ("Dallas", [], ""),
    ("New Orleans", [], ""), ("Boston", [], ""), ("Seattle", [], ""), ("Hawaii", [], ""), ("Alaska", [], ""),
    ("Texas", [], ""), ("California", [], ""), ("Florida", [], ""), ("Virginia", [], ""), ("West Virginia", [], ""),
    ("Maryland", [], ""), ("Pennsylvania", [], ""), ("Ohio", [], ""), ("Michigan", [], ""), ("Arizona", [], ""),
    ("Nevada", [], ""), ("Wisconsin", [], ""), ("North Carolina", [], ""), ("South Carolina", [], ""),
    ("New Jersey", [], ""), ("Delaware", [], ""), ("Massachusetts", [], ""), ("Illinois", [], ""), ("Colorado", [], ""),
    ("Utah", [], ""), ("Minnesota", [], ""), ("Iowa", [], ""), ("Missouri", [], ""), ("Tennessee", [], ""),
    ("Kentucky", [], ""), ("Louisiana", [], ""), ("Alabama", [], ""), ("Mississippi", [], ""), ("Oklahoma", [], ""),
    ("Kansas", [], ""), ("Nebraska", [], ""), ("Wyoming", [], ""), ("Montana", [], ""), ("Idaho", [], ""),
    ("Oregon", [], ""), ("New Mexico", [], ""), ("Arkansas", [], ""), ("Indiana", [], ""), ("Connecticut", [], ""),
    ("Middle East", ["Mideast", "Near East"], ""), ("Latin America", ["South America", "Central America"], ""),
    ("Caribbean", [], ""), ("Europe", [], ""), ("Africa", ["Sub-Saharan Africa"], ""), ("Sahel", [], ""),
    ("Horn of Africa", [], ""), ("Persian Gulf", ["Arabian Gulf"], ""), ("Balkans", [], ""), ("Caucasus", [], ""),
    ("Central Asia", [], ""), ("Southeast Asia", ["South East Asia"], ""), ("Scandinavia", ["Nordic countries"], ""),
    ("Arctic", [], ""), ("Antarctica", [], ""), ("Kashmir", [], ""), ("Kurdistan", ["Iraqi Kurdistan", "Kurdish region"], ""),
    ("Crimea", [], ""), ("Donbas", ["Donbass", "Donetsk", "Luhansk"], ""), ("Chechnya", [], ""), ("Tibet", [], ""),
    ("Xinjiang", [], ""), ("South China Sea", [], ""), ("Strait of Hormuz", [], ""), ("Golan Heights", [], ""),
    ("Waziristan / FATA", ["Waziristan", "FATA", "Tribal Areas"], ""),
]

PLACE = [(n, a, "") for n, a in _countries] + _places

PERSON = [
    # United States presidents and vice presidents
    ("Harry S. Truman", ["Truman", "Harry Truman", "President Truman"], "U.S. President 1945–1953."),
    ("Dwight D. Eisenhower", ["Eisenhower", "President Eisenhower", "Dwight Eisenhower"], "U.S. President 1953–1961; Allied commander in Europe in World War II."),
    ("John F. Kennedy", ["John F. Kennedy", "President Kennedy", "John Kennedy", "JFK"], "U.S. President 1961–1963; assassinated in Dallas on November 22, 1963."),
    ("Lyndon B. Johnson", ["Lyndon Johnson", "Lyndon B. Johnson", "LBJ", "President Johnson"], "U.S. President 1963–1969."),
    ("Richard Nixon", ["Nixon", "Richard M. Nixon", "President Nixon"], "U.S. President 1969–1974; resigned over Watergate."),
    ("Gerald Ford", ["Gerald Ford", "President Ford", "Gerald R. Ford"], "U.S. President 1974–1977."),
    ("Jimmy Carter", ["Jimmy Carter", "President Carter"], "U.S. President 1977–1981."),
    ("Ronald Reagan", ["Reagan", "President Reagan", "Ronald W. Reagan"], "U.S. President 1981–1989."),
    ("George H. W. Bush", ["George H.W. Bush", "George H. W. Bush", "George Herbert Walker Bush", "Bush Sr."], "U.S. President 1989–1993; Director of Central Intelligence 1976–1977."),
    ("Bill Clinton", ["Bill Clinton", "President Clinton", "William Jefferson Clinton", "William J. Clinton"], "U.S. President 1993–2001."),
    ("George W. Bush", ["President Bush", "George W. Bush", "Bush administration", "George Bush"], "U.S. President 2001–2009."),
    ("Barack Obama", ["Obama", "President Obama", "Barack H. Obama"], "U.S. President 2009–2017."),
    ("Donald Trump", ["Donald Trump", "President Trump", "Donald J. Trump"], "U.S. President 2017–2021 and from 2025."),
    ("Joe Biden", ["Joe Biden", "President Biden", "Joseph R. Biden", "Vice President Biden", "Joseph Biden"], "U.S. President 2021–2025; Vice President 2009–2017."),
    ("Dick Cheney", ["Cheney", "Vice President Cheney"], "U.S. Vice President 2001–2009; Secretary of Defense 1989–1993."),
    ("Al Gore", ["Al Gore", "Vice President Gore"], "U.S. Vice President 1993–2001."),
    ("Kamala Harris", ["Kamala Harris", "Vice President Harris"], "U.S. Vice President 2021–2025."),
    ("Mike Pence", ["Mike Pence", "Vice President Pence"], "U.S. Vice President 2017–2021."),
    ("JD Vance", ["JD Vance", "J.D. Vance", "Vice President Vance"], "U.S. Vice President from 2025."),
    ("Henry Kissinger", ["Kissinger", "Henry A. Kissinger"], "U.S. National Security Advisor 1969–1975 and Secretary of State 1973–1977."),
    # United Kingdom
    ("Winston Churchill", ["Churchill"], "UK Prime Minister 1940–1945 and 1951–1955."),
    ("Clement Attlee", ["Attlee"], "UK Prime Minister 1945–1951."),
    ("Harold Macmillan", ["Harold Macmillan"], "UK Prime Minister 1957–1963."),
    ("Harold Wilson", ["Harold Wilson"], "UK Prime Minister 1964–1970 and 1974–1976."),
    ("Edward Heath", ["Edward Heath", "Ted Heath"], "UK Prime Minister 1970–1974."),
    ("Margaret Thatcher", ["Thatcher", "Margaret Thatcher"], "UK Prime Minister 1979–1990."),
    ("John Major", ["John Major"], "UK Prime Minister 1990–1997."),
    ("Tony Blair", ["Tony Blair"], "UK Prime Minister 1997–2007."),
    ("Gordon Brown", ["Gordon Brown"], "UK Prime Minister 2007–2010."),
    ("David Cameron", ["David Cameron"], "UK Prime Minister 2010–2016."),
    ("Theresa May", ["Theresa May"], "UK Prime Minister 2016–2019."),
    ("Boris Johnson", ["Boris Johnson"], "UK Prime Minister 2019–2022."),
    ("Rishi Sunak", ["Sunak", "Rishi Sunak"], "UK Prime Minister 2022–2024."),
    ("Keir Starmer", ["Starmer", "Keir Starmer"], "UK Prime Minister from 2024."),
    # Europe
    ("Konrad Adenauer", ["Adenauer"], "First Chancellor of West Germany, 1949–1963."),
    ("Willy Brandt", ["Willy Brandt"], "West German Chancellor 1969–1974."),
    ("Helmut Kohl", ["Kohl", "Helmut Kohl"], "German Chancellor 1982–1998."),
    ("Gerhard Schröder", ["Schröder", "Schroeder", "Gerhard Schroeder"], "German Chancellor 1998–2005."),
    ("Angela Merkel", ["Merkel", "Chancellor Merkel"], "German Chancellor 2005–2021."),
    ("Olaf Scholz", ["Scholz", "Olaf Scholz"], "German Chancellor 2021–2025."),
    ("Friedrich Merz", ["Friedrich Merz"], "German Chancellor from 2025."),
    ("Charles de Gaulle", ["de Gaulle", "De Gaulle", "Charles de Gaulle"], "President of France 1959–1969."),
    ("François Mitterrand", ["Mitterrand", "Francois Mitterrand"], "President of France 1981–1995."),
    ("Jacques Chirac", ["Chirac"], "President of France 1995–2007."),
    ("Nicolas Sarkozy", ["Sarkozy"], "President of France 2007–2012."),
    ("François Hollande", ["Hollande", "Francois Hollande"], "President of France 2012–2017."),
    ("Emmanuel Macron", ["Macron", "Emmanuel Macron"], "President of France from 2017."),
    ("Marine Le Pen", ["Marine Le Pen"], "French far-right politician; leader of the National Front / National Rally."),
    ("Silvio Berlusconi", ["Berlusconi"], "Prime Minister of Italy (several terms, 1994–2011)."),
    ("Giorgia Meloni", ["Meloni", "Giorgia Meloni"], "Prime Minister of Italy from 2022."),
    ("Mario Draghi", ["Draghi", "Mario Draghi"], "President of the European Central Bank 2011–2019; Prime Minister of Italy 2021–2022."),
    ("Viktor Orbán", ["Orbán", "Orban", "Viktor Orban"], "Prime Minister of Hungary 1998–2002 and from 2010."),
    # Russia / USSR / Ukraine
    ("Joseph Stalin", ["Stalin"], "Leader of the Soviet Union 1920s–1953."),
    ("Nikita Khrushchev", ["Khrushchev", "Khrushchov"], "Soviet leader 1953–1964."),
    ("Leonid Brezhnev", ["Brezhnev"], "Soviet leader 1964–1982."),
    ("Yuri Andropov", ["Andropov"], "KGB chairman 1967–1982; Soviet leader 1982–1984."),
    ("Mikhail Gorbachev", ["Gorbachev"], "Soviet leader 1985–1991."),
    ("Boris Yeltsin", ["Yeltsin"], "President of Russia 1991–1999."),
    ("Vladimir Putin", ["Putin"], "President of Russia 2000–2008 and from 2012; Prime Minister 1999–2000 and 2008–2012."),
    ("Dmitry Medvedev", ["Medvedev"], "President of Russia 2008–2012; Prime Minister 2012–2020."),
    ("Sergei Lavrov", ["Lavrov"], "Russian Foreign Minister from 2004."),
    ("Volodymyr Zelensky", ["Zelensky", "Zelenskyy", "Zelenskiy"], "President of Ukraine from 2019."),
    ("Petro Poroshenko", ["Poroshenko"], "President of Ukraine 2014–2019."),
    ("Viktor Yanukovych", ["Yanukovych", "Yanukovich"], "President of Ukraine 2010–2014."),
    ("Alexander Lukashenko", ["Lukashenko"], "President of Belarus from 1994."),
    # Asia
    ("Mao Zedong", ["Mao Zedong", "Mao Tse-tung", "Chairman Mao"], "Founder of the People's Republic of China; its leader 1949–1976."),
    ("Zhou Enlai", ["Zhou Enlai", "Chou En-lai"], "Premier of the People's Republic of China 1949–1976."),
    ("Deng Xiaoping", ["Deng Xiaoping"], "Paramount leader of China from the late 1970s to the early 1990s."),
    ("Jiang Zemin", ["Jiang Zemin"], "General Secretary of the Chinese Communist Party 1989–2002; President 1993–2003."),
    ("Hu Jintao", ["Hu Jintao"], "President of China 2003–2013."),
    ("Xi Jinping", ["Xi Jinping"], "General Secretary of the Chinese Communist Party from 2012; President of China from 2013."),
    ("Shinzo Abe", ["Shinzo Abe", "Abe Shinzo", "Prime Minister Abe"], "Prime Minister of Japan 2006–2007 and 2012–2020."),
    ("Kim Il Sung", ["Kim Il Sung", "Kim Il-sung"], "Founding leader of North Korea, 1948–1994."),
    ("Kim Jong Il", ["Kim Jong Il", "Kim Jong-il"], "Leader of North Korea 1994–2011."),
    ("Kim Jong Un", ["Kim Jong Un", "Kim Jong-un"], "Leader of North Korea from 2011."),
    ("Jawaharlal Nehru", ["Nehru"], "First Prime Minister of India, 1947–1964."),
    ("Indira Gandhi", ["Indira Gandhi"], "Prime Minister of India 1966–1977 and 1980–1984."),
    ("Manmohan Singh", ["Manmohan Singh"], "Prime Minister of India 2004–2014."),
    ("Narendra Modi", ["Modi", "Narendra Modi"], "Prime Minister of India from 2014."),
    ("Benazir Bhutto", ["Benazir Bhutto"], "Prime Minister of Pakistan 1988–1990 and 1993–1996; assassinated in 2007."),
    ("Nawaz Sharif", ["Nawaz Sharif"], "Prime Minister of Pakistan three times; disqualified in 2017 in a case arising from the Panama Papers."),
    ("Pervez Musharraf", ["Musharraf"], "President of Pakistan 2001–2008."),
    ("Asif Ali Zardari", ["Zardari"], "President of Pakistan 2008–2013 and from 2024."),
    ("Imran Khan", ["Imran Khan"], "Prime Minister of Pakistan 2018–2022."),
    ("Hamid Karzai", ["Karzai"], "President of Afghanistan 2004–2014."),
    ("Ashraf Ghani", ["Ashraf Ghani"], "President of Afghanistan 2014–2021."),
    ("Susilo Bambang Yudhoyono", ["Yudhoyono"], "President of Indonesia 2004–2014."),
    ("Rodrigo Duterte", ["Duterte"], "President of the Philippines 2016–2022."),
    # Middle East / North Africa
    ("Mohammad Reza Pahlavi", ["Shah of Iran", "Mohammad Reza Shah", "Mohammad Reza Pahlavi"], "Shah of Iran until the 1979 revolution."),
    ("Ruhollah Khomeini", ["Khomeini", "Ayatollah Khomeini"], "Leader of the 1979 Iranian revolution; Supreme Leader 1979–1989."),
    ("Ali Khamenei", ["Khamenei"], "Supreme Leader of Iran from 1989."),
    ("Mohammad Khatami", ["Khatami"], "President of Iran 1997–2005."),
    ("Mahmoud Ahmadinejad", ["Ahmadinejad", "Ahmadinezhad"], "President of Iran 2005–2013."),
    ("Hassan Rouhani", ["Rouhani", "Rohani"], "President of Iran 2013–2021."),
    ("Ebrahim Raisi", ["Raisi"], "President of Iran 2021–2024."),
    ("Saddam Hussein", ["Saddam"], "President of Iraq 1979–2003; executed in 2006."),
    ("Nouri al-Maliki", ["Maliki"], "Prime Minister of Iraq 2006–2014."),
    ("Hafez al-Assad", ["Hafez al-Assad", "Hafez Assad"], "President of Syria 1971–2000."),
    ("Bashar al-Assad", ["Bashar al-Assad", "Assad"], "President of Syria 2000–2024."),
    ("Muammar Qaddafi", ["Qaddafi", "Qadhafi", "Gaddafi", "Gadhafi"], "Leader of Libya 1969–2011."),
    ("Gamal Abdel Nasser", ["Nasser"], "President of Egypt 1956–1970."),
    ("Anwar Sadat", ["Sadat"], "President of Egypt 1970–1981; assassinated in 1981."),
    ("Hosni Mubarak", ["Mubarak"], "President of Egypt 1981–2011."),
    ("Mohamed Morsi", ["Morsi", "Mursi"], "President of Egypt 2012–2013."),
    ("Abdel Fattah el-Sisi", ["Sisi", "el-Sisi", "al-Sisi"], "President of Egypt from 2014."),
    ("Recep Tayyip Erdoğan", ["Erdogan", "Erdoğan"], "Prime Minister of Turkey 2003–2014; President from 2014."),
    ("King Abdullah (Saudi Arabia)", ["King Abdullah bin Abdulaziz"], "King of Saudi Arabia 2005–2015."),
    ("King Salman", ["King Salman", "Salman bin Abdulaziz"], "King of Saudi Arabia from 2015."),
    ("Mohammed bin Salman", ["Mohammed bin Salman", "Mohammad bin Salman", "MBS"], "Crown Prince of Saudi Arabia from 2017."),
    ("David Ben-Gurion", ["Ben-Gurion", "Ben Gurion"], "First Prime Minister of Israel."),
    ("Golda Meir", ["Golda Meir"], "Prime Minister of Israel 1969–1974."),
    ("Menachem Begin", ["Menachem Begin"], "Prime Minister of Israel 1977–1983."),
    ("Yitzhak Rabin", ["Rabin"], "Prime Minister of Israel 1974–1977 and 1992–1995; assassinated in 1995."),
    ("Shimon Peres", ["Peres"], "Prime Minister and later President of Israel."),
    ("Ariel Sharon", ["Ariel Sharon"], "Prime Minister of Israel 2001–2006."),
    ("Ehud Olmert", ["Olmert"], "Prime Minister of Israel 2006–2009."),
    ("Ehud Barak", ["Ehud Barak"], "Prime Minister of Israel 1999–2001; later Defense Minister."),
    ("Benjamin Netanyahu", ["Netanyahu", "Bibi Netanyahu"], "Prime Minister of Israel 1996–1999, 2009–2021 and from 2022."),
    ("Yasser Arafat", ["Arafat"], "Chairman of the PLO; President of the Palestinian Authority until his death in 2004."),
    ("Mahmoud Abbas", ["Mahmoud Abbas", "Abu Mazen"], "President of the Palestinian Authority from 2005."),
    # Africa
    ("Nelson Mandela", ["Mandela"], "President of South Africa 1994–1999."),
    ("Meles Zenawi", ["Meles Zenawi", "Meles"], "Prime Minister of Ethiopia 1995–2012."),
    ("Robert Mugabe", ["Mugabe"], "Leader of Zimbabwe 1980–2017."),
    ("Patrice Lumumba", ["Lumumba"], "First Prime Minister of the Congo; killed in 1961."),
    ("Mobutu Sese Seko", ["Mobutu"], "Ruler of Zaire (Congo) 1965–1997."),
    # Americas
    ("Fidel Castro", ["Fidel Castro", "Fidel"], "Leader of Cuba 1959–2008."),
    ("Raúl Castro", ["Raul Castro", "Raúl Castro"], "Leader of Cuba 2008–2018."),
    ("Hugo Chávez", ["Chavez", "Chávez"], "President of Venezuela 1999–2013."),
    ("Nicolás Maduro", ["Maduro"], "President of Venezuela from 2013."),
    ("Luiz Inácio Lula da Silva", ["Lula", "Lula da Silva"], "President of Brazil 2003–2010 and from 2023."),
    ("Dilma Rousseff", ["Rousseff", "Dilma"], "President of Brazil 2011–2016."),
    ("Jair Bolsonaro", ["Bolsonaro"], "President of Brazil 2019–2022."),
    ("Felipe Calderón", ["Calderón", "Calderon"], "President of Mexico 2006–2012."),
    ("Enrique Peña Nieto", ["Peña Nieto", "Pena Nieto"], "President of Mexico 2012–2018."),
    ("Andrés Manuel López Obrador", ["López Obrador", "Lopez Obrador", "AMLO"], "President of Mexico 2018–2024."),
    ("Juan Perón", ["Perón", "Peron"], "President of Argentina 1946–1955 and 1973–1974."),
    ("Cristina Fernández de Kirchner", ["Cristina Kirchner", "Cristina Fernández", "Fernández de Kirchner"], "President of Argentina 2007–2015."),
    ("Javier Milei", ["Milei"], "President of Argentina from 2023."),
    ("Salvador Allende", ["Allende"], "President of Chile 1970–1973; died during the 1973 coup."),
    ("Augusto Pinochet", ["Pinochet"], "Chilean dictator 1973–1990."),
    ("Manuel Noriega", ["Noriega"], "Military ruler of Panama, ousted by the 1989 U.S. invasion."),
    ("Daniel Ortega", ["Daniel Ortega"], "Nicaraguan Sandinista leader; President 1985–1990 and from 2007."),
    ("Álvaro Uribe", ["Uribe", "Alvaro Uribe"], "President of Colombia 2002–2010."),
    ("Justin Trudeau", ["Justin Trudeau"], "Prime Minister of Canada 2015–2025."),
    ("Stephen Harper", ["Stephen Harper"], "Prime Minister of Canada 2006–2015."),
    # International
    ("Kofi Annan", ["Kofi Annan"], "UN Secretary-General 1997–2006."),
    ("Ban Ki-moon", ["Ban Ki-moon", "Ban Ki-Moon", "Ban Ki Moon"], "UN Secretary-General 2007–2016."),
    ("António Guterres", ["Guterres", "Antonio Guterres"], "UN Secretary-General from 2017."),
    ("Pope Francis", ["Pope Francis"], "Pope 2013–2025."),
    ("Pope Benedict XVI", ["Pope Benedict", "Benedict XVI"], "Pope 2005–2013."),
    ("Pope John Paul II", ["John Paul II"], "Pope 1978–2005."),
    # Militant leaders
    ("Osama bin Laden", ["bin Laden", "Bin Laden", "Usama bin Laden", "Bin Ladin", "bin Ladin", "UBL", "Osama bin Ladin"], "Founder of al-Qaida; killed in Abbottabad, Pakistan in May 2011."),
    ("Ayman al-Zawahiri", ["Zawahiri", "Zawahri"], "al-Qaida deputy, then leader 2011–2022."),
    ("Abu Musab al-Zarqawi", ["Zarqawi"], "Leader of al-Qaida in Iraq; killed 2006."),
    ("Anwar al-Awlaki", ["Awlaki", "Aulaqi"], "U.S.-born AQAP cleric killed in a 2011 drone strike."),
    ("Khalid Sheikh Mohammed", ["Khalid Sheikh Mohammed", "Khalid Shaykh Muhammad", "KSM"], "Alleged architect of the 9/11 attacks; held at Guantanamo."),
    ("Abu Bakr al-Baghdadi", ["Baghdadi"], "Leader of ISIS/ISIL; killed in 2019."),
    ("Hassan Nasrallah", ["Nasrallah"], "Secretary-General of Hezbollah 1992–2024."),
    ("Mullah Omar", ["Mullah Omar", "Mullah Mohammed Omar"], "Founding leader of the Taliban."),
    ("Yahya Sinwar", ["Sinwar"], "Hamas leader in Gaza; killed in 2024."),
    # Publishers and sources of leaks
    ("Julian Assange", ["Assange"], "WikiLeaks founder."),
    ("Chelsea Manning", ["Bradley Manning", "Chelsea Manning", "PFC Manning"], "U.S. Army analyst who leaked documents to WikiLeaks in 2010."),
    ("Edward Snowden", ["Snowden", "Edward J. Snowden", "Ed Snowden"], "Former NSA contractor who provided NSA documents to journalists in 2013."),
    ("Daniel Ellsberg", ["Ellsberg"], "Military analyst who leaked the Pentagon Papers in 1971."),
    ("Reality Winner", ["Reality Winner"], "NSA contractor convicted in 2018 of leaking a report on Russian election interference."),
    ("Joshua Schulte", ["Joshua Schulte", "Schulte"], "Former CIA software engineer convicted of leaking the Vault 7 hacking tools to WikiLeaks."),
]

ORGANIZATION = [
    ("United Nations", ["UN", "U.N.", "United Nations", "UNSC", "Security Council", "UN Security Council", "UN General Assembly"], "The United Nations, including the Security Council."),
    ("UNHCR", ["UN Refugee Agency", "United Nations High Commissioner for Refugees"], "UN refugee agency."),
    ("UN Human Rights Council", ["Human Rights Council", "UN Human Rights Commission", "OHCHR"], "UN human rights bodies."),
    ("World Health Organization", ["World Health Organization", "World Health Organisation"], "UN health agency."),
    ("IAEA", ["International Atomic Energy Agency"], "International Atomic Energy Agency (nuclear inspections)."),
    ("NATO", ["North Atlantic Treaty Organization"], "North Atlantic Treaty Organization."),
    ("European Union", ["EU", "European Union", "European Commission", "European Parliament", "European Council", "EEC", "European Community"], "European Union institutions."),
    ("OSCE", ["Organization for Security and Co-operation in Europe"], "Organization for Security and Co-operation in Europe."),
    ("OECD", ["Organisation for Economic Co-operation and Development", "Organization for Economic Cooperation and Development"], "Organisation for Economic Co-operation and Development."),
    ("G7 / G8", ["G7", "G8", "G-7", "G-8", "Group of Seven", "Group of Eight"], "Group of Seven / Eight leading economies."),
    ("G20", ["G20", "G-20", "Group of Twenty"], "Group of Twenty major economies."),
    ("OPEC", ["Organization of the Petroleum Exporting Countries"], "Organization of the Petroleum Exporting Countries."),
    ("World Bank", ["World Bank", "IBRD"], "International development lender."),
    ("IMF", ["International Monetary Fund"], "International Monetary Fund."),
    ("WTO", ["World Trade Organization", "World Trade Organisation"], "World Trade Organization."),
    ("Interpol", ["INTERPOL", "Interpol"], "International Criminal Police Organization."),
    ("International Criminal Court", ["International Criminal Court", "ICC"], "Permanent international court for genocide, war crimes and crimes against humanity (The Hague)."),
    ("International Court of Justice", ["International Court of Justice", "ICJ", "World Court"], "The UN's principal court (The Hague)."),
    ("African Union", ["African Union", "Organization of African Unity"], "African Union (formerly the OAU)."),
    ("Arab League", ["Arab League", "League of Arab States"], "League of Arab States."),
    ("Gulf Cooperation Council", ["Gulf Cooperation Council", "GCC"], "Gulf Cooperation Council."),
    ("ASEAN", ["Association of Southeast Asian Nations"], "Association of Southeast Asian Nations."),
    ("Organization of American States", ["Organization of American States", "OAS"], "Organization of American States."),
    ("Red Cross", ["Red Cross", "ICRC", "International Committee of the Red Cross", "Red Crescent"], "International Red Cross and Red Crescent movement."),
    ("Amnesty International", ["Amnesty International"], "Human rights organization."),
    ("Human Rights Watch", ["Human Rights Watch", "HRW"], "Human rights organization."),
    ("ACLU", ["ACLU", "American Civil Liberties Union"], "American Civil Liberties Union."),
    ("EFF", ["EFF", "Electronic Frontier Foundation"], "Electronic Frontier Foundation (digital civil liberties)."),
    ("Communist Party of China", ["Chinese Communist Party", "CCP", "Communist Party of China"], "Ruling party of the People's Republic of China."),
    ("Communist Party of the Soviet Union", ["Communist Party of the Soviet Union", "CPSU"], "Ruling party of the USSR."),
    ("Warsaw Pact", ["Warsaw Pact"], "Soviet-led military alliance, 1955–1991."),
    ("PLO", ["Palestine Liberation Organization", "Fatah"], "Palestine Liberation Organization / Fatah."),
    # militant and criminal groups
    ("al-Qaida", ["al-Qa'ida", "al-Qaida", "al Qaida", "al-Qaeda", "al Qaeda", "Al Qaeda", "Al-Qaeda", "Al-Qa'ida", "AQ", "Al Qaida"], "Jihadist network founded by Osama bin Laden."),
    ("AQAP", ["al-Qa'ida in the Arabian Peninsula", "al-Qaeda in the Arabian Peninsula"], "al-Qaida in the Arabian Peninsula (Yemen)."),
    ("AQIM", ["al-Qa'ida in the Islamic Maghreb", "al-Qaeda in the Islamic Maghreb"], "al-Qaida in the Islamic Maghreb."),
    ("al-Qaida in Iraq", ["al-Qaida in Iraq", "al-Qaeda in Iraq", "AQI"], "al-Qaida's Iraqi branch, forerunner of ISIS."),
    ("al-Shabaab", ["al-Shabaab", "al-Shabab", "Al-Shabaab", "al Shabaab", "Al Shabaab"], "Somali jihadist group."),
    ("Taliban", ["Taliban", "Taleban"], "Afghan/Pakistani Taliban; ruled Afghanistan 1996–2001 and again from 2021."),
    ("Hezbollah", ["Hizballah", "Hezbollah", "Hizbollah", "Hizbullah"], "Lebanese Shia militant group and political party."),
    ("Hamas", ["HAMAS", "Hamas"], "Palestinian Islamist movement; governed Gaza from 2007."),
    ("Palestinian Islamic Jihad", ["Palestinian Islamic Jihad", "PIJ"], "Palestinian militant group."),
    ("ISIS / ISIL", ["ISIL", "ISIS", "Islamic State", "Daesh", "DAESH"], "Islamic State."),
    ("Houthis", ["Houthi", "Houthis", "Ansar Allah"], "Yemeni Zaydi movement (Ansar Allah)."),
    ("Boko Haram", ["Boko Haram"], "Nigerian jihadist group."),
    ("Lashkar-e-Taiba", ["Lashkar-e-Tayyiba", "Lashkar-e-Taiba", "LeT"], "Pakistan-based militant group."),
    ("Haqqani Network", ["Haqqani", "Haqqani Network"], "Afghan/Pakistani militant network."),
    ("Jemaah Islamiyah", ["Jemaah Islamiyah"], "Southeast Asian jihadist network."),
    ("Abu Sayyaf", ["Abu Sayyaf"], "Philippine militant group."),
    ("Hayat Tahrir al-Sham", ["Hayat Tahrir al-Sham", "HTS", "Jabhat al-Nusra", "Nusra Front", "al-Nusra"], "Syrian jihadist group (formerly al-Nusra Front)."),
    ("FARC", ["FARC"], "Revolutionary Armed Forces of Colombia."),
    ("ELN", ["National Liberation Army (Colombia)"], "Colombian guerrilla group."),
    ("Shining Path", ["Shining Path", "Sendero Luminoso"], "Peruvian Maoist insurgency."),
    ("PKK", ["PKK", "Kurdistan Workers' Party"], "Kurdistan Workers' Party."),
    ("Muslim Brotherhood", ["Muslim Brotherhood"], "Islamist movement, Egypt and region."),
    ("IRA", ["Irish Republican Army", "Provisional IRA"], "Irish Republican Army."),
    ("ETA", ["Euskadi Ta Askatasuna"], "Basque separatist group."),
    ("LTTE", ["Tamil Tigers", "Liberation Tigers of Tamil Eelam"], "Sri Lankan Tamil insurgency."),
    ("Sinaloa Cartel", ["Sinaloa Cartel", "Sinaloa cartel"], "Mexican drug trafficking organization."),
    ("Los Zetas", ["Los Zetas", "Zetas"], "Mexican drug trafficking organization."),
    ("CJNG", ["Jalisco New Generation Cartel", "Jalisco Cartel"], "Mexican drug trafficking organization."),
    ("Medellín Cartel", ["Medellin Cartel", "Medellín Cartel"], "Colombian cocaine cartel led by Pablo Escobar."),
    ("Cali Cartel", ["Cali Cartel"], "Colombian cocaine cartel."),
    ("MS-13", ["MS-13", "Mara Salvatrucha"], "Transnational street gang."),
    ("Wagner Group", ["Wagner Group", "Wagner PMC", "PMC Wagner"], "Russian private military company."),
    # leaks, transparency and press
    ("WikiLeaks", ["Wikileaks", "WikiLeaks"], "Publisher of leaked documents."),
    ("Distributed Denial of Secrets", ["Distributed Denial of Secrets", "DDoSecrets", "DDOSecrets"], "Transparency collective that publishes leaked and hacked datasets."),
    ("ICIJ", ["International Consortium of Investigative Journalists"], "International Consortium of Investigative Journalists (Panama, Paradise and Pandora Papers)."),
    ("OCCRP", ["Organized Crime and Corruption Reporting Project"], "Organized Crime and Corruption Reporting Project."),
    ("Anonymous / hacktivists", ["Anonymous", "LulzSec", "hacktivist", "hacktivists"], "Hacktivist collectives."),
    ("Bellingcat", ["Bellingcat"], "Open-source investigations collective."),
    ("Transparency International", ["Transparency International"], "Anti-corruption organization."),
    ("Tor Project", ["Tor Project"], "Nonprofit that develops the Tor anonymity network."),
    ("Al Jazeera", ["Al Jazeera", "Al-Jazeera", "Aljazeera"], "Qatar-based broadcaster."),
    ("The New York Times", ["New York Times", "NYT", "The Times (NY)"], "U.S. newspaper."),
    ("The Washington Post", ["Washington Post"], "U.S. newspaper."),
    ("The Wall Street Journal", ["Wall Street Journal", "WSJ"], "U.S. newspaper."),
    ("The Guardian", ["The Guardian", "Guardian newspaper"], "UK newspaper."),
    ("The Intercept", ["The Intercept"], "U.S. investigative news site."),
    ("Der Spiegel", ["Der Spiegel", "Spiegel"], "German news magazine."),
    ("Süddeutsche Zeitung", ["Süddeutsche Zeitung", "Sueddeutsche Zeitung"], "German newspaper that received the Panama Papers."),
    ("Le Monde", ["Le Monde"], "French newspaper."),
    ("BBC", ["British Broadcasting Corporation", "BBC News"], "British public broadcaster."),
    ("CNN", ["CNN"], "U.S. cable news network."),
    ("Fox News", ["Fox News"], "U.S. cable news network."),
    ("Reuters", ["Reuters"], "News agency."),
    ("Associated Press", ["Associated Press", "AP News"], "News agency."),
    ("ProPublica", ["ProPublica"], "U.S. investigative newsroom."),
    ("RT / Sputnik", ["Russia Today", "Sputnik News"], "Russian state media."),
]

AGENCY = [
    # foreign intelligence and security services (U.S. agencies are in the government pack)
    ("GCHQ", ["Government Communications Headquarters"], "UK signals intelligence agency (Cheltenham)."),
    ("MI5", ["MI5"], "UK Security Service (domestic)."),
    ("MI6", ["MI6", "Secret Intelligence Service", "SIS"], "UK Secret Intelligence Service (foreign)."),
    ("CSEC", ["CSE", "Communications Security Establishment"], "Canada's signals intelligence agency (CSEC, renamed CSE)."),
    ("CSIS", ["Canadian Security Intelligence Service"], "Canada's security intelligence service."),
    ("ASD/DSD", ["ASD", "DSD", "Australian Signals Directorate", "Defence Signals Directorate"], "Australia's signals intelligence agency (DSD, renamed ASD in 2013)."),
    ("ASIS", ["Australian Secret Intelligence Service"], "Australia's foreign intelligence service."),
    ("GCSB", ["Government Communications Security Bureau"], "New Zealand's signals intelligence agency."),
    ("Five Eyes", ["FVEY", "5-Eyes", "5 Eyes", "UKUSA", "Five Eyes"], "The UKUSA intelligence alliance: USA, UK, Canada, Australia, New Zealand."),
    ("BND", ["Bundesnachrichtendienst"], "Germany's foreign intelligence service."),
    ("BfV", ["Bundesamt für Verfassungsschutz", "Verfassungsschutz"], "Germany's domestic intelligence agency."),
    ("Stasi", ["Stasi", "Ministerium für Staatssicherheit", "East German Ministry for State Security"], "East German secret police and intelligence service."),
    ("FRA", ["Försvarets radioanstalt", "National Defence Radio Establishment"], "Sweden's signals intelligence agency."),
    ("DGSE", ["Direction Générale de la Sécurité Extérieure", "Direction Generale de la Securite Exterieure"], "France's foreign intelligence service."),
    ("DGSI", ["Direction générale de la Sécurité intérieure", "DCRI"], "France's domestic intelligence service."),
    ("Danish DDIS", ["DDIS", "Danish Defence Intelligence Service", "FE (Denmark)"], "Denmark's defence intelligence service."),
    ("AIVD/MIVD", ["AIVD", "MIVD"], "Dutch intelligence and security services."),
    ("Mossad", ["Mossad"], "Israel's foreign intelligence service."),
    ("Shin Bet", ["Shin Bet", "Shabak", "Israel Security Agency"], "Israel's internal security service."),
    ("ISNU (Unit 8200)", ["ISNU", "Israeli SIGINT National Unit", "Unit 8200"], "Israel's signals intelligence unit."),
    ("KGB", ["KGB", "Committee for State Security"], "Soviet intelligence and security service until 1991."),
    ("FSB", ["FSB", "Federal Security Service"], "Russia's domestic security service (KGB successor)."),
    ("SVR", ["SVR", "Foreign Intelligence Service of Russia"], "Russia's foreign intelligence service."),
    ("GRU", ["GRU", "Main Intelligence Directorate"], "Russian military intelligence."),
    ("Ministry of State Security (China)", ["Ministry of State Security", "MSS"], "China's civilian intelligence service."),
    ("People's Liberation Army", ["PLA", "People's Liberation Army"], "China's armed forces, including their intelligence and cyber units."),
    ("Pakistani ISI", ["Inter-Services Intelligence", "ISI"], "Pakistan's Inter-Services Intelligence."),
    ("India RAW", ["Research and Analysis Wing", "R&AW"], "India's foreign intelligence agency."),
    ("IRGC", ["Islamic Revolutionary Guard Corps", "Revolutionary Guard", "Revolutionary Guards", "Pasdaran"], "Iran's Islamic Revolutionary Guard Corps."),
    ("Quds Force", ["Quds Force", "Qods Force", "IRGC-QF"], "The IRGC's external operations branch."),
    ("MOIS (Iran)", ["MOIS", "Ministry of Intelligence and Security", "VEVAK"], "Iran's Ministry of Intelligence."),
    ("Saudi GIP", ["General Intelligence Presidency", "Saudi intelligence"], "Saudi Arabia's foreign intelligence service."),
    ("Cuban DGI", ["Dirección General de Inteligencia", "Cuban intelligence"], "Cuba's intelligence service."),
    ("Europol", ["Europol"], "EU police cooperation agency."),
]

COMPANY = [
    ("Google", ["Google", "Gmail", "GMail", "Alphabet Inc."], "Internet company."),
    ("Yahoo", ["Yahoo!", "Yahoo", "YAHOO"], "Internet company."),
    ("Microsoft", ["Microsoft", "Hotmail", "Outlook.com", "MSN"], "Software company."),
    ("Apple", ["Apple", "Apple Inc."], "Technology company."),
    ("Facebook", ["Facebook", "Meta Platforms", "Instagram", "WhatsApp"], "Social network company (Meta), including Instagram and WhatsApp."),
    ("Twitter", ["Twitter"], "Social network (renamed X in 2023)."),
    ("Amazon", ["Amazon.com", "Amazon Web Services", "AWS"], "E-commerce and cloud company."),
    ("LinkedIn", ["LinkedIn", "Linkedin"], "Professional network."),
    ("YouTube", ["YouTube", "Youtube"], "Video service owned by Google."),
    ("Skype", ["Skype"], "VoIP service (Microsoft from 2011)."),
    ("Dropbox", ["Dropbox"], "Cloud storage service."),
    ("TikTok / ByteDance", ["TikTok", "ByteDance"], "Chinese-owned social video company."),
    ("Telegram (messenger)", ["Telegram Messenger"], "Messaging service."),
    ("Verizon", ["Verizon"], "U.S. telecom."),
    ("AT&T", ["AT&T"], "U.S. telecom."),
    ("Huawei", ["Huawei", "HUAWEI"], "Chinese telecom equipment maker."),
    ("ZTE", ["ZTE"], "Chinese telecom equipment maker."),
    ("Cisco", ["Cisco", "CISCO", "Cisco Systems"], "Network equipment maker."),
    ("Kaspersky", ["Kaspersky", "Kaspersky Lab"], "Russian antivirus vendor."),
    ("Booz Allen Hamilton", ["Booz Allen", "Booz Allen Hamilton"], "U.S. consulting firm and intelligence contractor."),
    ("Palantir", ["Palantir"], "Data-analysis software company and government contractor."),
    ("Lockheed Martin", ["Lockheed Martin", "Lockheed"], "U.S. defense contractor."),
    ("Raytheon", ["Raytheon", "RTX"], "U.S. defense contractor."),
    ("Northrop Grumman", ["Northrop Grumman", "Northrop"], "U.S. defense contractor."),
    ("Boeing", ["Boeing"], "Aerospace and defense company."),
    ("General Dynamics", ["General Dynamics"], "U.S. defense contractor."),
    ("BAE Systems", ["BAE Systems", "BAE"], "British defense contractor."),
    ("Airbus", ["Airbus", "EADS"], "European aerospace and defense company."),
    ("Halliburton / KBR", ["Halliburton", "KBR", "Kellogg Brown & Root"], "Oilfield services company and its former contracting arm."),
    ("Blackwater", ["Blackwater", "Xe Services", "Academi"], "U.S. private military contractor."),
    ("DynCorp", ["DynCorp"], "U.S. private military contractor."),
    ("NSO Group", ["NSO Group", "Pegasus spyware"], "Israeli spyware maker (Pegasus)."),
    ("Hacking Team", ["Hacking Team", "HackingTeam"], "Italian surveillance-software vendor, itself hacked in 2015."),
    ("Gamma Group / FinFisher", ["Gamma Group", "FinFisher", "FinSpy", "Gamma International"], "Surveillance-software vendor (FinFisher)."),
    ("Crypto AG", ["Crypto AG"], "Swiss cipher-machine maker secretly owned by the CIA and BND (Operation Rubicon)."),
    ("Stratfor", ["Stratfor", "Strategic Forecasting"], "Private intelligence firm whose emails WikiLeaks published (Global Intelligence Files)."),
    ("Cambridge Analytica", ["Cambridge Analytica", "SCL Group"], "Political data firm."),
    ("Gazprom", ["Gazprom"], "Russian state gas company."),
    ("Rosneft", ["Rosneft"], "Russian state oil company."),
    ("Lukoil", ["Lukoil", "LUKoil"], "Russian oil company."),
    ("Saudi Aramco", ["Saudi Aramco", "Aramco"], "Saudi state oil company."),
    ("ExxonMobil", ["ExxonMobil", "Exxon", "Mobil"], "Oil company."),
    ("Chevron", ["Chevron"], "Oil company."),
    ("Shell", ["Royal Dutch Shell", "Shell plc", "Shell Oil"], "Oil company."),
    ("BP", ["British Petroleum", "BP plc"], "Oil company."),
    ("TotalEnergies", ["TotalEnergies", "Total S.A.", "Total SA"], "French oil company."),
    ("Petrobras", ["Petrobras"], "Brazilian state oil company."),
    ("PDVSA", ["Petróleos de Venezuela", "Petroleos de Venezuela"], "Venezuelan state oil company."),
    ("Pemex", ["Pemex"], "Mexican state oil company."),
    ("Glencore", ["Glencore"], "Commodity trader and miner."),
    ("Trafigura", ["Trafigura"], "Commodity trader."),
    ("Vitol", ["Vitol"], "Commodity trader."),
    ("HSBC", ["HSBC"], "British bank."),
    ("UBS", ["UBS"], "Swiss bank."),
    ("Credit Suisse", ["Credit Suisse"], "Swiss bank (taken over by UBS in 2023)."),
    ("Deutsche Bank", ["Deutsche Bank"], "German bank."),
    ("JPMorgan Chase", ["JPMorgan", "JP Morgan", "J.P. Morgan", "JPMorgan Chase"], "U.S. bank."),
    ("Goldman Sachs", ["Goldman Sachs"], "U.S. investment bank."),
    ("Citigroup", ["Citigroup", "Citibank", "Citi"], "U.S. bank."),
    ("Bank of America", ["Bank of America", "BofA"], "U.S. bank."),
    ("Morgan Stanley", ["Morgan Stanley"], "U.S. investment bank."),
    ("Wells Fargo", ["Wells Fargo"], "U.S. bank."),
    ("Barclays", ["Barclays"], "British bank."),
    ("BNP Paribas", ["BNP Paribas"], "French bank."),
    ("Société Générale", ["Société Générale", "Societe Generale"], "French bank."),
    ("Standard Chartered", ["Standard Chartered"], "British bank."),
    ("Danske Bank", ["Danske Bank"], "Danish bank."),
    ("Mastercard", ["MasterCard", "Mastercard"], "Payment network."),
    ("Western Union", ["Western Union"], "Money transfer company."),
    ("PayPal", ["PayPal"], "Online payments company."),
    ("Sony", ["Sony"], "Japanese electronics and entertainment company."),
    ("Samsung", ["Samsung"], "Korean electronics conglomerate."),
    ("Nokia", ["Nokia"], "Phone and network equipment maker."),
    ("Ericsson", ["Ericsson"], "Telecom equipment maker."),
    ("Siemens", ["Siemens"], "German conglomerate."),
]

ENTITIES = {"person": PERSON, "agency": AGENCY, "organization": ORGANIZATION, "company": COMPANY, "place": PLACE}

# Broad themes for any corpus. A document is tagged when it has MIN_IDEA_HITS regex hits.
IDEAS = [
    ("Corruption & bribery", [r"(?i:\bcorrupt)", r"(?i:\bbrib)", r"(?i:\bkickback)", r"(?i:\bembezzl)", r"(?i:\bgraft\b)", r"(?i:\bnepotis)", r"(?i:\bcronyism\b)"],
     "Bribery, embezzlement, kickbacks and abuse of office."),
    ("Human rights abuses", [r"(?i:\bhuman rights\b)", r"(?i:\bextrajudicial)", r"(?i:\bdisappear(?:ed|ance))", r"(?i:\bpersecut)", r"(?i:\bgenocide\b)", r"(?i:\bethnic cleansing\b)", r"(?i:\bwar crimes?\b)"],
     "Human rights violations, war crimes and persecution."),
    ("Torture & detention", [r"(?i:\btortur)", r"(?i:\bwaterboard)", r"(?i:\binterrogat)", r"(?i:\bdetainee)", r"(?i:\brendition\b)", r"(?i:\bblack site)", r"(?i:\bsolitary confinement\b)"],
     "Detention, interrogation, rendition and torture."),
    ("Elections & voting", [r"(?i:\belection)", r"(?i:\bballot)", r"(?i:\bvoter)", r"(?i:\bvoting\b)", r"(?i:\bcampaign\b)", r"(?i:\bpolling station)", r"(?i:\belectoral\b)"],
     "Elections, campaigns and voting."),
    ("Sanctions & embargoes", [r"(?i:\bsanction)", r"(?i:\bembargo)", r"\bOFAC\b", r"(?i:\bblacklist)", r"(?i:\basset freeze)", r"(?i:\bexport control)"],
     "Sanctions, embargoes and export controls."),
    ("Nuclear weapons & proliferation", [r"(?i:\bnuclear weapon)", r"(?i:\bproliferat)", r"(?i:\benrichment\b)", r"(?i:\buranium\b)", r"(?i:\bplutonium\b)", r"(?i:\bwarhead)", r"(?i:\bcentrifuge)"],
     "Nuclear weapons programs and nonproliferation."),
    ("Chemical & biological weapons", [r"(?i:\bchemical weapon)", r"(?i:\bnerve agent)", r"(?i:\bsarin\b)", r"(?i:\bbiological weapon)", r"(?i:\bbioweapon)", r"(?i:\banthrax\b)", r"\bVX\b", r"(?i:\bnovichok\b)"],
     "Chemical and biological weapons."),
    ("Terrorism", [r"(?i:\bterroris)", r"(?i:\bcounterterror)", r"(?i:\bjihad)", r"(?i:\bsuicide bomb)", r"(?i:\bextremis)", r"(?i:\bradicali)"],
     "Terrorism and counterterrorism."),
    ("Arms trade", [r"(?i:\barms (?:sale|deal|trade|transfer|export))", r"(?i:\bweapons? (?:sale|deal|transfer|shipment))", r"(?i:\barms dealer)", r"(?i:\bsmuggl\w* (?:arms|weapons))"],
     "Arms sales, transfers and trafficking."),
    ("Money laundering", [r"(?i:\blaunder)", r"(?i:\bshell compan)", r"(?i:\bsuspicious activity report)", r"\bAML\b", r"(?i:\bbeneficial owner)"],
     "Money laundering and concealment of assets."),
    ("Drugs & trafficking", [r"(?i:\bnarcotic)", r"(?i:\bcocaine\b)", r"(?i:\bheroin\b)", r"(?i:\bdrug traffick)", r"(?i:\bcartel\b)", r"(?i:\bopium\b)", r"(?i:\bfentanyl\b)", r"(?i:\bhuman trafficking\b)"],
     "Drug and human trafficking."),
    ("Censorship & press freedom", [r"(?i:\bcensor)", r"(?i:\bpress freedom\b)", r"(?i:\bjournalists?\b)", r"(?i:\bfreedom of (?:speech|expression))", r"(?i:\bblocked websites?\b)"],
     "Censorship, journalists and freedom of expression."),
    ("Disinformation & propaganda", [r"(?i:\bdisinformation\b)", r"(?i:\bmisinformation\b)", r"(?i:\bpropaganda\b)", r"(?i:\bfake news\b)", r"(?i:\binfluence operation)", r"(?i:\btroll farm)"],
     "Disinformation, propaganda and influence operations."),
    ("Hacking & cyber attacks", [r"(?i:\bhack(?:ed|er|ers|ing)\b)", r"(?i:\bcyber ?attack)", r"(?i:\bmalware\b)", r"(?i:\bransomware\b)", r"(?i:\bphishing\b)", r"(?i:\bbreach(?:ed)?\b)", r"\bDDoS\b"],
     "Hacking, data breaches and cyber attacks."),
    ("Coups & regime change", [r"(?i:\bcoup\b)", r"(?i:\bcoup d'[eé]tat)", r"(?i:\bregime change\b)", r"(?i:\bjunta\b)", r"(?i:\boverthrow)", r"(?i:\binsurrection)"],
     "Coups, insurrections and regime change."),
    ("Protests & unrest", [r"(?i:\bprotest)", r"(?i:\bdemonstrat(?:ion|ors))", r"(?i:\briot)", r"(?i:\buprising\b)", r"(?i:\bunrest\b)", r"(?i:\bcrackdown\b)"],
     "Protests, uprisings and crackdowns."),
    ("Refugees & migration", [r"(?i:\brefugee)", r"(?i:\basylum\b)", r"(?i:\bmigrant)", r"(?i:\bmigration\b)", r"(?i:\bdeport)", r"(?i:\bdisplaced persons?\b)"],
     "Refugees, asylum and migration."),
    ("Oil, gas & energy", [r"(?i:\boil\b)", r"(?i:\bpetroleum\b)", r"(?i:\bnatural gas\b)", r"(?i:\bpipeline)", r"\bLNG\b", r"(?i:\brefiner)", r"(?i:\benergy security\b)"],
     "Oil, gas, pipelines and energy security."),
    ("Health & pandemics", [r"(?i:\bpandemic)", r"(?i:\bepidemic)", r"\bCOVID", r"(?i:\bcoronavirus\b)", r"\bEbola\b", r"(?i:\bvaccin)", r"\bH1N1\b|\bH5N1\b"],
     "Public health crises and pandemics."),
    ("Climate & environment", [r"(?i:\bclimate change\b)", r"(?i:\bglobal warming\b)", r"(?i:\bemissions\b)", r"(?i:\bcarbon\b)", r"(?i:\bdeforestation\b)", r"(?i:\bpollution\b)"],
     "Climate change and the environment."),
]
MIN_IDEA_HITS = 3
